# Generated by Django 4.1.3 on 2023-02-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='500', max_length=225),
            preserve_default=False,
        ),
    ]
